name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
repository: https://github.com/flutter/packages/tree/main/packages/video_player/video_player
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.9.2
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: video_player_android
      ios:
        default_package: video_player_avfoundation
      macos:
        default_package: video_player_avfoundation
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  video_player_android: #^2.3.5
    git:
      url: git@github.com:xbwlai/packages.git
      path: packages/video_player/video_player_android
      ref: video_player_android-v2.7.6_caching+1
  video_player_avfoundation: #^2.5.6
    git:
      url: git@github.com:xbwlai/packages.git
      path: packages/video_player/video_player_avfoundation
      ref: video_player_avfoundation-v2.6.1_caching+2
  video_player_platform_interface: #^6.2.0
    git:
      url: git@github.com:xbwlai/packages.git
      path: packages/video_player/video_player_platform_interface
      ref: video_player_platform_interface-v6.2.3_caching+1
  video_player_web: #^2.1.0
    git:
      url: git@github.com:xbwlai/packages.git
      path: packages/video_player/video_player_web
      ref: video_player_web-v2.3.2_caching+1

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - video
  - video-player
